config/routes.rb
Rails.application.routes.draw do
	root to: 'pages#home'

	get 'pages/home'
	put 'admin/:id' => 'profiles#make_admin', :as => "make_admin"
	put 'student/:id' => 'profiles#make_student', :as => "make_student"
	post 'pairs' => 'pairs#save_into_db', :as => "save_into_db"

	resources :pairs, :profiles

  devise_for :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pair.rb
class Pair < ApplicationRecord

end

app/models/pairing.rb
class Pairing
	attr_reader :days

	def initialize(students)
		@days = {}
		pairing(students)
	end

	private

	def pairing(students)																			# pass in the argument of array students
		students.push("*RUBBER DUCK*") if students.size.odd?		#adds one more element("*RUBBER DUCK*") to students array if we have odd number of student
		days = students.size - 1																# number of times round-robin rotates until reaching the original position
		pairs_of_the_day = students.size / 2										# number of unique possible pairs for each day
		days.times do |key|
			@days[key] = []																				# every iteration generates new hash element with an empty array like so, @days[0] = []
			pairs_of_the_day.times do |students_index|									# iterates for putting in pairs
				@days[key] << [students[students_index], students.reverse[students_index]]     # insert an array of [students[0], students.reverse[0]],
																														#[students[1],[students.reverse[1]]...and so forth.
			end

			students = [students[0]] + students[1..-1].rotate(-1)     # round robin logic. Fix the position of students[0], and rotate the remainings.
																																# students[-1] element comes into the position of student[1]
		end
	end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
	validates_presence_of :first_name, :last_name, :role, :user

	def full_name
    "#{first_name} #{last_name}"
	end

	def partial_full_name
		"#{first_name} #{last_name[0]}."
	end

	def make_admin
	  profile = Profile.find params[:id]
	  profile.update( :role => "admin" )
	  redirect_to profiles_url
	end

	def make_student
	  profile = Profile.find params[:id]
	  profile.update( :role => "student" )
	  redirect_to profiles_url
	end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile, :dependent => :destroy, :inverse_of => :user
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         validates_presence_of :password, :email
  def has_profile?
        profile.present? && profile.persisted?
  end

  def full_name
  	profile.full_name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
		redirection
  end

	private

	def redirection
		if current_user.profile == nil
			redirect_to new_profile_path
		elsif current_user.profile.role == "admin"
			redirect_to pairs_path
		else
			@pairs_schedule = Pair.all
		end
	end
end

app/controllers/pairs_controller.rb
class PairsController < ApplicationController

	def index
		@pairs_schedule = Pair.all
	end

	def create
	end

	def save_into_db
		set_students_array
		Pair.all.where("day >= :today", today: Date.today ).destroy_all
															# Destroy data that is from today
		@schedule = Pairing.new(@students.shuffle).days
															# shuffle the array for randomizing the order
		@schedule.each do |day, pairs|
			Pair.create!(day: Date.today + day, pairs: pairs)
		end
		redirect_to pairs_path
	end

	private

	def pairs_params
		params.require(:pair).permit(:day, :pairs)
	end

	def set_students_array
		@students = []									# set students empty array
		profiles = Profile.all 					# Profile.all because we specify
		 																# role in the profile class
		profiles.each do |profile|
				@students <<  profile.full_name if profile.role == "student"
																				# insert each Profile with role
																				# student with full name
		end
	end

end

app/controllers/profile_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update, :show]
  before_action :authenticate_user!

  def index
    @profiles = Profile.all.order(:role , :first_name)
    render json: @profiles

  end

  def show
    @profile = Profile.find(params[:id])
  end

  def change_status
    @profile = Profile.find(params[:id])

    if @profile.role == "student" 
      @profile.role = "admin"
      @profile.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { render json: @profile }
      end
    else
      @profile.role = "student"
      @profile.save

      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { render json: @profile }
      end
    end
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
    else
      render :edit
    end
  end


  private
    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :role)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :set_profile, only: [:edit, :update, :show]

  def index
    @profiles = Profile.all.order(:role, :first_name)
  end

	def show
		@profile = Profile.find(params[:id])
	end

	def new
		 @profile = Profile.new
	end

	def create
		@profile = current_user.build_profile(profile_params)

		if @profile.save
			redirect_to root_path, notice: "Profile successfully created, contact your teacher for a confirmation"
		else
			render :new
		end
	end

	def update
		if @profile.update(profile_params)
			redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
		else
			render :edit
		end
	end

	def make_admin
		profile = User.find(params[:id]).profile
		profile.update( :role => "admin" )
		redirect_to profiles_url
	end

	def make_student
		profile = User.find(params[:id]).profile
		profile.update( :role => "student" )
		redirect_to profiles_url
	end

	private

	def set_profile
		@profile = current_user.profile
	end

	def profile_params
		params.require(:profile).permit(:first_name, :last_name, :role)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pairs_helper.rb
module PairsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Matchmaker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
		<%= render "shared/navbar" %>

	  <p class="notice"><%= notice %></p>
	  <p class="alert"><%= alert %></p>

	  <div class="container">
	    <%= yield %>
  	</div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Hello, <%= current_user.profile.first_name %>!</h1>
<table class="table table-striped table-bordered">
	<tr>
		<th>Day</th>
		<th>Your pair for the day</th>
	</tr>
	<% @pairs_schedule.each do |day| %>
		<% if day.day <= Date.today %>
			<% day.pairs.each do |pair| %>
				<% if pair.include?(current_user.profile.full_name) %>
					<tr>
						<td><%= day.day %></td>
						<td><%= pair.join(" & ") %></td>
					</tr>
				<% end %>
			<% end %>
		<% end %>
	<% end %>
</table>

app/views/pairs/index.html.erb
<h1>Hello, <%= current_user.profile.first_name %>! </h1>
<h2>Here are the pairing schedule of students!</h2>

<table class="table table-striped table-bordered">
	<% @pairs_schedule.sort.each do |day| %>
	<tr>
		<td><%= day.day %></td>
		<% day.pairs.each do |pair| %>
		<td><%= pair.join(" & ") %></td>
			<% end %>
	</tr>
	<% end %>
</table>

<%= button_to "auto generate", save_into_db_path %>

app/views/profiles/_admin.html.erb
<table class="table table-striped table-bordered">
	<% @profiles.each do |profile| %>
	  <tr style="text-align: center;">
	    <td> <%= profile.full_name %></td>
	    <td> <%= profile.role %></td>
	    <td> <%= button_to "Make admin", {action: "make_admin", data: { confirm: 'Are you sure?' }, id: profile.user.id }, method: :put, class: "btn-danger" %></td>
	    <td> <%= button_to "Make student", {action: "make_student", data: { confirm: 'Are you sure?' }, id: profile.user.id }, method: :put, class: "btn-warning" %></td>
	  </tr>
	<% end %>
</table>

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
  <% @profile.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger"><%= msg %></p>
  <% end %>

  <div class="form-group">
    <label>First Name</label>
    <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
  </div>

  <div class="form-group">

    <%= f.hidden_field :role, value: "user" , class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary", :confirm => "Thank you for registering, one of our teachers will contact you with more information" %>
    <%= link_to "Back", new_profile_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/profiles/_student.html.erb
<table class="table">
<% @profiles.each do |profile| %>

  <tr>
    <td> <%= profile.full_name %></td>
    <td> <%= profile.role %></td>
  </tr>
  <% end %>
  </table>

app/views/profiles/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Edit your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/profiles/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><h1><%= @profile %></h1></div>

  <div class="panel-body">

    <% if current_user.profile.role == "admin" %>
    <%= render 'admin'%>
    <% else %>
    <%= render 'student'%>
    <% end %>

  </div>
</div>

app/views/profiles/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Create your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><h1><%= @profile.full_name %></h1></div>

  <div class="panel-body">

      <% if @profile && @profile.student? %>
      <%=render 'showstudent'%>
      <% else %>
     <%= render 'showadmin'%>
      <% end %>

  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Match Maker", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
    <%= current_user.has_profile? ? current_user.full_name : current_user.email  %> <span class="caret"></span></a>

  <ul class="dropdown-menu">

    <% if current_user.has_profile? %>


      <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>


      <li><%= link_to "Edit Password", edit_user_registration_path %></li>

      <li><%= link_to "User list", profiles_path %></li>
      <% else %>
        <li><%= link_to "Create Profile", new_profile_path %></li>
  <% end %>
    <li role="separator" class="divider"></li>
    <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
  </ul>

</li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>